Tycho r2.0.1+
greatscottgadgets/tycho pull request #14
Opened 2024-04-09 21:08 UTC by yhetti

2024-04-16 12:55 UTC, martinling requested changes
With the new footprint for U4, pins 1, 2, 4, 5 and 9 now have tracks running onto them that are wider than the pads. These tracks should be reduced so that the fabricated pads consistently have the width defined in the footprint.

![image](https://github.com/greatscottgadgets/tycho/assets/673823/9e31f09f-7a33-41b1-9d98-2d644f231001)

For the same reasons, I think it would be better to remove the GND polygon around pin 3, and run a track into this pin instead. When trying to rework this part, the extra heat capacity of the GND net was a significant issue.

On Cynthion we do have a polygon around pin 3, but we also have a polygon around pin 8 which serves to balance it out on the opposite corner. On Tycho we don't have this option, as pin 8 is in use to disable the switch, rather than being permanently grounded.

On the User.Drawings layer, the 92mm dimension on the right is no longer aligned with the holes. Its value is correct but it has been shifted upward slightly. The new dimensions look OK. Should there perhaps be one for the 24V socket too?

I think that the TPS55288 footprint is still not quite correct. The top edges of pads 1 and 19 do not line up with the top edges of pads 20-23.

2024-04-16 14:23 UTC, mossmann requested changes
The U6 footprint is much improved, but I would also like to see silkscreen, fab, and courtyard layers added to it. I've requested some other small changes as well.

2024-04-16 14:23 UTC, mossmann commented on tycho/tycho.kicad_pro
> +    "VERSION": "r2.0.1+"
This is fine, but in the future please try to remember to update the version with a "+" before making any other changes.

2024-04-16 14:23 UTC, mossmann commented on tycho/tycho.kicad_pcb
> +    (fp_text value "22k" (at 2.1 0 -180) (layer "F.Fab")
The change to the R65 value is layout/schematic parity fix for r2.0.1. This is fine, but in the future try to make such changes first before updating the version to "+".

2024-04-16 14:23 UTC, mossmann commented on tycho/tycho.kicad_pcb
> +    (fp_text value "PI3USB102G" (at 0 2 180) (layer "F.Fab")
Please hide the U4 Value on F.Fab.

2024-04-16 14:23 UTC, mossmann commented on tycho/tycho.kicad_pcb
> +    (fp_text reference "U4" (at 0 -2 180) (layer "F.SilkS")
Please fix the "U4" silkscreen conflict on F.SilkS.

2024-04-16 14:27 UTC, mossmann commented
This isn't specific to this PR in particular, but I would like .kicad_prl files removed from the repo and added to .gitignore.

2024-04-26 15:40 UTC, mossmann requested changes
The U6 footprint updates look good.

Only one end of the 92 mm dimension was corrected, making the dimension value incorrect.

The trace widths escaping from U4 are generally improved, but I would like to see pins 1 and 2 routed nicely like pins 4 and 5, avoiding the excess pin 1 pad width.

Fix the clearance violations introduced by the changes to `D_SW1+` and `D_SW1-` routing. These can be fixed by refilling zones.

Always run DRC and refill zones before creating or updating a pull request.

Remove the zone around U4 pin 3. A commit message says this was done, but the zone is still there.

Restore the `HOST_VBUS` zone that became unfilled. This can be fixed by refilling zones.

Add a dimension for the 24 V socket (J8) as @martinling suggested.

2024-04-27 02:03 UTC, martinling commented
The dedicated polygon around U4 pin 3 was removed, but the main GND polygon for the top layer still fills some of the area around this pin. To get a clean track running into that pin it's necessary to add a keepout area.

![image](https://github.com/greatscottgadgets/tycho/assets/673823/087c4e7a-eeee-4c2e-bdd8-34bdd800c610)
![image](https://github.com/greatscottgadgets/tycho/assets/673823/a61261a2-fd7b-471a-881f-c5b26aa035ba)

I have this change in 633c8e664edbbf24113529f95da32f2e54311757 if you want it.

2024-04-29 12:36 UTC, mossmann requested changes
The updates look good, but please add a keepout to U4 pin 3 as @martinling suggested.

2024-04-30 19:40 UTC, mossmann approved these changes
Looks good. Thank you!

2024-04-30 19:41 UTC, merged